import type { StudyItem, Subject } from './types';

const source = {
  british:{name:'British Council LearnEnglish',url:'https://learnenglish.britishcouncil.org/'},
  cambridge:{name:'Cambridge Dictionary',url:'https://dictionary.cambridge.org/'},
  khan:{name:'Khan Academy',url:'https://www.khanacademy.org/math'},
  openstax:{name:'OpenStax',url:'https://openstax.org/subjects/math'}
};

export const ITEMS:StudyItem[] = [
  {id:'en-request-intent',subject:'english',skillId:'en-requests',title:'Natural requests',kind:'choice',prompt:'“Could you send me the report by Friday?” What is the speaker doing?',options:['Making a polite request','Describing a past event','Giving a strict command'],answer:0,explanation:'“Could you…?” is a common way to make a request politely. The context and verb matter more than memorizing one translation.',difficulty:2,estimatedSeconds:35,source:source.british,tags:['grammar','functional-language']},
  {id:'en-present-perfect',subject:'english',skillId:'en-tenses',title:'Meaning in context',kind:'choice',prompt:'“I have been studying for two hours.” Which meaning fits best?',options:['The studying started earlier and is still relevant/continuing now.','The studying happened only yesterday.','The studying will start in two hours.'],answer:0,explanation:'The present perfect continuous links an activity that began in the past with the present.',difficulty:3,estimatedSeconds:45,source:source.british,tags:['grammar','context']},
  {id:'en-listen-report',subject:'english',skillId:'en-listening',title:'Listening checkpoint',kind:'listen',prompt:'Listen to the sentence and then state the main intention.',target:'Could you send me the report by Friday?',hint:'Listen for the request and the deadline.',explanation:'The core meaning is a polite request to send a report before Friday.',difficulty:2,estimatedSeconds:40,source:source.british,tags:['listening']},
  {id:'en-speak-report',subject:'english',skillId:'en-speaking',title:'Speaking checkpoint',kind:'speak',prompt:'Say this sentence naturally:',target:'Could you send me the report by Friday?',hint:'Try connected speech instead of reading each word separately.',explanation:'The browser evaluation uses speech recognition as an initial production signal. It is not a phoneme-level pronunciation diagnosis.',difficulty:3,estimatedSeconds:55,source:source.british,tags:['speaking','fluency']},
  {id:'en-looking-forward',subject:'english',skillId:'en-vocabulary',title:'Useful expression',kind:'choice',prompt:'“I’m looking forward to the trip.” What does it express?',options:['Excitement or positive anticipation','Fear of traveling','A plan that was cancelled'],answer:0,explanation:'“Look forward to” expresses that you are happy or excited about something in the future.',difficulty:2,estimatedSeconds:35,source:source.cambridge,tags:['vocabulary']},
  {id:'en-collocation',subject:'english',skillId:'en-vocabulary',title:'Natural collocation',kind:'choice',prompt:'Which phrase sounds natural in English?',options:['make a decision','do a decision','build a decision'],answer:0,explanation:'“Make a decision” is the standard collocation.',difficulty:2,estimatedSeconds:35,source:source.cambridge,tags:['vocabulary','collocation']},
  {id:'en-listen-schedule',subject:'english',skillId:'en-listening',title:'Listening for detail',kind:'listen',prompt:'Listen and identify the key detail.',target:'The meeting starts at half past three, so please arrive ten minutes early.',hint:'Pay attention to the start time and arrival instruction.',explanation:'The meeting starts at 3:30 and the listener is asked to arrive ten minutes early.',difficulty:3,estimatedSeconds:45,source:source.british,tags:['listening','details']},
  {id:'en-speak-booking',subject:'english',skillId:'en-speaking',title:'Polite production',kind:'speak',prompt:'Say this sentence clearly:',target:'I’d like to book a table for two, please.',hint:'Keep “I’d like to…” smooth and stress the important nouns.',explanation:'The goal is understandable, natural production rather than perfect imitation.',difficulty:3,estimatedSeconds:55,source:source.british,tags:['speaking','fluency']},
  {id:'en-word-order',subject:'english',skillId:'en-tenses',title:'Build the sentence',kind:'choice',prompt:'Choose the natural sentence.',options:['She has already finished the task.','She already has finish the task.','She has finish already the task.'],answer:0,explanation:'“Has finished” forms the present perfect correctly, and “already” commonly sits before the past participle.',difficulty:3,estimatedSeconds:40,source:source.british,tags:['grammar']},
  {id:'en-explain-request',subject:'english',skillId:'en-requests',title:'Explain the choice',kind:'explain',prompt:'Why is “Could you open the window, please?” usually softer than “Open the window.”?',keywords:['request','polite','softer','could','command'],hint:'Explain the difference in social function, not just the translation.',explanation:'“Could you…?” frames the action as a request and gives the listener more social choice than a bare imperative.',difficulty:4,estimatedSeconds:75,source:source.british,tags:['production','grammar']},
  {id:'en-comprehension-context',subject:'english',skillId:'en-comprehension',title:'Context transfer',kind:'choice',prompt:'A coworker says: “I’m tied up right now, but I can call you after lunch.” What should you expect?',options:['They are busy now and may call later.','They are leaving work immediately.','They are asking you to call before lunch.'],answer:0,explanation:'“Tied up” here means busy or occupied. The second clause gives the expected later action.',difficulty:4,estimatedSeconds:50,source:source.cambridge,tags:['comprehension','context']},
  {id:'en-input-plural',subject:'english',skillId:'en-vocabulary',title:'Production: irregular plural',kind:'input',prompt:'Type the plural form of “child”.',answer:'children',explanation:'“Children” is the irregular plural of “child”.',difficulty:2,estimatedSeconds:25,source:source.cambridge,tags:['vocabulary','production']},

  {id:'math-discount',subject:'math',skillId:'math-percentages',title:'Discount with meaning',kind:'input',prompt:'A store gives 20% off a product that costs R$ 150. What is the final price?',answer:'120',hint:'20% is one fifth of the original price. Find the discount, then subtract it.',explanation:'20% of 150 is 30. The final price is 150 − 30 = 120.',difficulty:2,estimatedSeconds:55,source:source.khan,tags:['percentage','calculation']},
  {id:'math-discount-transfer',subject:'math',skillId:'math-percentages',title:'Transfer the concept',kind:'choice',prompt:'The same 20% discount is applied to R$ 80. What is the final price?',options:['R$ 60','R$ 64','R$ 68'],answer:1,explanation:'After a 20% discount, 80% remains. 80 × 0.8 = 64.',difficulty:3,estimatedSeconds:45,source:source.khan,tags:['percentage','transfer']},
  {id:'math-increase',subject:'math',skillId:'math-percentages',title:'Percentage increase',kind:'input',prompt:'A price of 200 increases by 15%. What is the new price?',answer:'230',explanation:'15% of 200 is 30, so the new price is 230.',difficulty:3,estimatedSeconds:55,source:source.khan,tags:['percentage']},
  {id:'math-explain-percent',subject:'math',skillId:'math-percentages',title:'Explain 0.8',kind:'explain',prompt:'Why does multiplying a price by 0.8 produce the price after a 20% discount?',keywords:['100','20','80','percent','remaining','0.8'],hint:'Connect the percentage that is removed with the percentage that remains.',explanation:'A 20% discount leaves 80% of the original amount. Eighty percent written as a decimal is 0.8.',difficulty:4,estimatedSeconds:80,source:source.khan,tags:['reasoning','percentage']},
  {id:'math-fraction-decimal',subject:'math',skillId:'math-number-sense',title:'Fraction to decimal',kind:'choice',prompt:'Which decimal is equal to 3/4?',options:['0.25','0.75','1.25'],answer:1,explanation:'3 divided by 4 equals 0.75.',difficulty:2,estimatedSeconds:35,source:source.openstax,tags:['fractions','number-sense']},
  {id:'math-ratio',subject:'math',skillId:'math-ratios',title:'Ratio reasoning',kind:'input',prompt:'The ratio of blue to red balls is 2:3. If there are 12 red balls, how many blue balls are there?',answer:'8',explanation:'12 red balls represent 3 parts, so one part is 4 and blue is 2 × 4 = 8.',difficulty:3,estimatedSeconds:55,source:source.khan,tags:['ratio','reasoning']},
  {id:'math-equation',subject:'math',skillId:'math-equations',title:'Solve and verify',kind:'input',prompt:'Solve: 3x + 5 = 20. What is x?',answer:'5',explanation:'Subtract 5 to get 3x = 15, then divide by 3: x = 5.',difficulty:2,estimatedSeconds:50,source:source.khan,tags:['algebra','equations']},
  {id:'math-equation-transfer',subject:'math',skillId:'math-equations',title:'Transfer the method',kind:'choice',prompt:'Which equation has the same solution x = 5?',options:['2x + 1 = 11','2x + 1 = 8','x + 5 = 5'],answer:0,explanation:'2(5) + 1 = 11, so the first equation is true when x = 5.',difficulty:3,estimatedSeconds:45,source:source.khan,tags:['algebra','transfer']},
  {id:'math-rate',subject:'math',skillId:'math-rates',title:'Unit rate',kind:'input',prompt:'A car travels 180 km in 3 hours at a constant rate. What is the rate in km/h?',answer:'60',explanation:'Rate is distance divided by time: 180 ÷ 3 = 60 km/h.',difficulty:2,estimatedSeconds:45,source:source.khan,tags:['rate','division']},
  {id:'math-probability',subject:'math',skillId:'math-probability',title:'Probability in context',kind:'choice',prompt:'A fair six-sided die is rolled once. What is the probability of getting an even number?',options:['1/6','1/3','1/2'],answer:2,explanation:'There are three even outcomes (2, 4, 6) out of six equally likely outcomes: 3/6 = 1/2.',difficulty:3,estimatedSeconds:50,source:source.openstax,tags:['probability']},
  {id:'math-area',subject:'math',skillId:'math-geometry',title:'Area with units',kind:'input',prompt:'A rectangle is 8 m long and 3 m wide. What is its area in square meters?',answer:'24',explanation:'Area is length × width: 8 × 3 = 24 m².',difficulty:2,estimatedSeconds:40,source:source.khan,tags:['geometry','units']},
  {id:'math-word-problem',subject:'math',skillId:'math-modeling',title:'Multi-step model',kind:'input',prompt:'A subscription costs R$ 40 per month plus a one-time R$ 15 setup fee. How much do 3 months cost in total?',answer:'135',explanation:'Three monthly payments cost 3 × 40 = 120. Add the one-time 15: total 135.',difficulty:4,estimatedSeconds:70,source:source.khan,tags:['modeling','multi-step']},
  {id:'math-explain-equation',subject:'math',skillId:'math-equations',title:'Explain an inverse operation',kind:'explain',prompt:'Why do we divide by 3 after getting 3x = 15 when solving for x?',keywords:['divide','coefficient','inverse','3','15','x'],hint:'Explain what operation undoes multiplication by 3.',explanation:'Division by 3 is the inverse operation that isolates x because x is multiplied by 3.',difficulty:4,estimatedSeconds:80,source:source.openstax,tags:['reasoning','algebra']}
];

export const SUBJECT_INFO:Record<Subject,{label:string;short:string;description:string}> = {
  english:{label:'Inglês',short:'EN',description:'Ouça, fale, leia, escreva e transfira o que aprendeu.'},
  math:{label:'Matemática',short:'∑',description:'Entenda conceitos, calcule, visualize, explique e resolva.'}
};

export function getItem(id:string){return ITEMS.find(item=>item.id===id);}
export function getItemsForSubject(subject:Subject){return ITEMS.filter(item=>item.subject===subject);}
